// src/components/NavBar.vue
<template>
  <nav
    class="fixed top-0 z-20 flex h-[80px] w-full items-center justify-center border-b border-[#0000001f] bg-lsurface !bg-opacity-90 text-[#14142b] backdrop-blur-lg dark:border-[#ffffff1f] dark:bg-dbg dark:text-gray-300"
  >
    <div
      class="flex w-full max-w-[1000px] items-center justify-between px-4 lg:px-0"
    >
      <!-- Logo -->
      <header role="banner">
        <RouterLink
          class="group relative flex h-12 text-2xl font-bold text-ltext1 dark:text-dtext1"
          :to="{ name: 'Home' }"
          spy="{true}"
          smooth="{true}"
          offset="{0}"
          duration="{500}"
          isDynamic="{true}"
        >
          <RaloDev class="z-20 h-12 w-12 transition-all duration-500" />
          <div
            class="ms- pointer-events-none relative z-10 -translate-x-12 opacity-0 transition-all delay-100 duration-300 group-hover:translate-x-0 group-hover:opacity-100"
          >
            <span
              class="absolute -top-1 inline-block bg-gradient-to-br from-[#447ffa] to-[#2e57ac] bg-clip-text font-display font-bold text-transparent"
              >alo</span
            >
            <span class="absolute -bottom-1 text-xl font-normal text-[#af39cc]">
              /Dev
            </span>
          </div>
        </RouterLink>
      </header>
      <!-- Content -->
      <div class="flex flex-row">
        <!-- Desktop menu -->
        <div className="hidden md:flex code text-lg pe-8">
          <!-- TailwindCSS Dropdown HOME -->
          <div class="relative flex w-full flex-row">
            <ul class="flex gap-3">
              <li class="hover:text-lprimary dark:hover:text-dprimary">
                <RouterLink
                  class="border-b-2 text-ltext1 hover:text-primary dark:text-dtext1"
                  :to="{ name: 'Home' }"
                  active-class="border-b-2 border-primary dark:border-dprimary"
                  spy="{true}"
                  smooth="{true}"
                  offset="{0}"
                  duration="{500}"
                  isDynamic="{true}"
                >
                  Home
                </RouterLink>
              </li>
              <li class="hover:text-lprimary dark:hover:text-dprimary">
                <RouterLink
                  class="border-b-lprimary text-ltext1 hover:border-b-2 hover:text-lprimary dark:border-b-dprimary dark:text-dtext1 dark:hover:text-dprimary"
                  :to="{ name: 'Home', hash: '#experience' }"
                  spy="{true}"
                  smooth="{true}"
                  offset="{0}"
                  duration="{500}"
                  isDynamic="{true}"
                >
                  Experience
                </RouterLink>
              </li>
              <li class="hover:text-lprimary dark:hover:text-dprimary">
                <RouterLink
                  class="border-b-lprimary text-ltext1 hover:border-b-2 hover:text-lprimary dark:border-b-dprimary dark:text-dtext1 dark:hover:text-dprimary"
                  :to="{ name: 'Home', hash: '#services' }"
                  spy="{true}"
                  smooth="{true}"
                  offset="{0}"
                  duration="{500}"
                  isDynamic="{true}"
                >
                  Services
                </RouterLink>
              </li>

              <li class="hover:text-lprimary dark:hover:text-dprimary">
                <RouterLink
                  class="border-b-lprimary text-ltext1 hover:border-b-2 hover:text-lprimary dark:border-b-dprimary dark:text-dtext1 dark:hover:text-dprimary"
                  :to="{ name: 'Home', hash: '#about' }"
                  spy="{true}"
                  smooth="{true}"
                  offset="{0}"
                  duration="{500}"
                  isDynamic="{true}"
                >
                  About
                </RouterLink>
              </li>
              <li class="hover:text-lprimary dark:hover:text-dprimary">
                <RouterLink
                  class="border-b-lprimary text-ltext1 hover:border-b-2 hover:text-lprimary dark:border-b-dprimary dark:text-dtext1 dark:hover:text-dprimary"
                  :to="{ name: 'Home', hash: '#projects' }"
                  spy="{true}"
                  smooth="{true}"
                  offset="{0}"
                  duration="{500}"
                  isDynamic="{true}"
                >
                  Projects
                </RouterLink>
              </li>
              <li class="hover:text-lprimary dark:hover:text-dprimary">
                <RouterLink
                  class="border-b-lprimary text-ltext1 hover:border-b-2 hover:text-lprimary dark:border-b-dprimary dark:text-dtext1 dark:hover:text-dprimary"
                  :to="{ name: 'Home', hash: '#contact' }"
                  spy="{true}"
                  smooth="{true}"
                  offset="{0}"
                  duration="{500}"
                  isDynamic="{true}"
                >
                  Contact
                </RouterLink>
              </li>
            </ul>
          </div>
        </div>
        <!-- ThemeButton -->
        <SwitchThemeButton class="my-auto h-6 w-6 xl:me-0" />

        <!-- Mobile menu button -->
        <div
          @click="handleClick"
          class="z-10 my-auto ms-8 cursor-pointer md:hidden"
        >
          <svg
            v-if="open"
            class="text-ltext dark:text-dtext h-6 w-6"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 14 14"
          >
            <path
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"
            />
          </svg>
          <svg
            v-else
            class="text-ltext dark:text-dtext h-6 w-6"
            aria-hidden="true"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 17 14"
          >
            <path
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M1 1h15M1 7h15M1 13h15"
            />
          </svg>
        </div>
        <!-- Mobile menu -->
        <ul
          class="bg-lbg absolute left-0 top-0 flex h-screen w-full flex-col items-center justify-center transition-all duration-500 dark:bg-dbg"
          :class="[open ? 'opacity-100' : 'pointer-events-none opacity-0']"
        >
          <li v-for="link in links" :key="link.name">
            <RouterLink
              :to="link"
              exactActiveClass="border-b-2 border-[#60f7d4]"
              spy="{true}"
              smooth="{true}"
              offset="{0}"
              duration="{500}"
              isDynamic="{true}"
              class="dark:text-dtext text-ltext my-4 text-2xl"
              @click="handleClick"
            >
              {{ link.label }}
            </RouterLink>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>

<script lang="ts" setup>
import { ref } from 'vue'
import { RouterLink } from 'vue-router'
import SwitchThemeButton from './buttons/SwitchThemeButton.vue'
import RaloDev from './icons/RaloDev.vue'
const open = ref(false)

type LinkInterface = {
  name: string
  hash?: string
  label: string
}

defineProps({
  links: {
    type: Array as () => LinkInterface[],
    required: true
  }
})

const handleClick = () => {
  open.value = !open.value
}
</script>

// src/components/Navbar.jsx
import React, { useState } from 'react';
import { FaBars, FaTimes, FaGithub, FaLinkedin, FaTwitter } from 'react-icons/fa';
import { HiOutlineMail } from 'react-icons/hi';
import { BsFillPersonLinesFill } from 'react-icons/bs';
import Logo from '../assets/github.png';
import { Link } from 'react-scroll';

const Navbar = () => {
  const [open, setOpen] = useState(false);
  const handleClick = () => {
    setOpen(!open);
  };

  return (
    <nav className="fixed w-full h-[80px] flex justify-center items-center border-b border-[#ffffff1f] bg-[#0000001e] backdrop-blur-md	 text-gray-300 z-10">
      <div className="flex max-w-[1200px] w-full justify-between items-center px-4">
        <div>
          <span className="flex text-[#60f7d4] logo">R</span>
        </div>
        {/* Desktop menu */}
        <ul className="hidden md:block code text-lg [&>*]:cursor-pointer [&>*]:inline-block">
            <Link className="hover:text-[#60f7d4] link" activeClass="border-b-2 border-[#60f7d4]" to="home" spy={true} smooth={true} offset={0} duration={500} isDynamic={true}>
              Home
            </Link>
            <Link className="hover:text-[#60f7d4] link" activeClass="border-b-2 border-[#60f7d4]" to="about" spy={true} smooth={true} offset={0} duration={500} isDynamic={true}>
              About
            </Link>
            <Link className="hover:text-[#60f7d4] link" activeClass="border-b-2 border-[#60f7d4]" to="skills" spy={true} smooth={true} offset={0} duration={500} isDynamic={true}>
              Skills
            </Link>
            <Link className="hover:text-[#60f7d4] link" activeClass="border-b-2 border-[#60f7d4]" to="projects" spy={true} smooth={true} offset={0} duration={500} isDynamic={true}>
              Projects
            </Link>
            <Link className="hover:text-[#60f7d4] link" activeClass="border-b-2 border-[#60f7d4]" to="contact" spy={true} smooth={true} offset={0} duration={500} isDynamic={true}>
              Contact
            </Link>
        </ul>
        {/* Hambuerguer */}
        <div onClick={handleClick} className="md:hidden z-10 cursor-pointer">
          {open ? <FaTimes className="text-3xl" /> : <FaBars className="text-3xl" />}
        </div>
        {/* Mobile menu */}
        <ul
          className={`absolute flex top-0 left-0 w-full h-screen bg-[#0a192f] flex-col justify-center items-center transition-all duration-500 ${
            open ? 'opacity-100' : 'opacity-0 pointer-events-none'
          }`}>
          <li className="inline-block mx-2 py-6 text-4xl">
            <Link to='home' activeClass="border-b-2 border-[#60f7d4]" spy={true} smooth={true} offset={0} duration={500} isDynamic={true} onClick={handleClick}>Home</Link>
          </li>
          <li className="inline-block mx-2 py-6 text-4xl">
            <Link to='about' activeClass="border-b-2 border-[#60f7d4]" spy={true} smooth={true} offset={0} duration={500} isDynamic={true} onClick={handleClick}>About</Link>
          </li>
          <li className="inline-block mx-2 py-6 text-4xl">
            <Link to='skills' activeClass="border-b-2 border-[#60f7d4]" spy={true} smooth={true} offset={0} duration={500} isDynamic={true} onClick={handleClick}>Skills</Link>
          </li>
          <li className="inline-block mx-2 py-6 text-4xl">
            <Link to='projects' activeClass="border-b-2 border-[#60f7d4]" spy={true} smooth={true} offset={0} duration={500} isDynamic={true} onClick={handleClick}>Projects</Link>
          </li>
          <li className="inline-block mx-2 py-6 text-4xl">
            <Link to='contact' activeClass="border-b-2 border-[#60f7d4]" spy={true} smooth={true} offset={0} duration={500} isDynamic={true} onClick={handleClick}>Contact</Link>
          </li>
        </ul>
      </div>
    </nav>
  );
};

export default Navbar;
